/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package first.gui;

/**
 *
 * @author karmi
 */
public class Birthday extends javax.swing.JFrame {

    /**
     * Creates new form Birthday
     */
    public Birthday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Happy = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        namein = new javax.swing.JTextField();
        Day = new javax.swing.JLabel();
        Dayin = new javax.swing.JComboBox<String>();
        Month = new javax.swing.JLabel();
        Monthin = new javax.swing.JComboBox<String>();
        Year = new javax.swing.JLabel();
        Yearin = new javax.swing.JComboBox<String>();
        Done = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Output = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(null);

        Happy.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        Happy.setForeground(new java.awt.Color(204, 0, 0));
        Happy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Happy.setText("Happy Birthday!");
        Happy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Happy);
        Happy.setBounds(10, 22, 833, 62);

        Name.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name.setText("Name:");
        Name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Name);
        Name.setBounds(294, 107, 53, 24);

        namein.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        namein.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namein.setAlignmentX(0.0F);
        namein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameinActionPerformed(evt);
            }
        });
        getContentPane().add(namein);
        namein.setBounds(351, 102, 266, 34);

        Day.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Day.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Day.setText("Day:");
        getContentPane().add(Day);
        Day.setBounds(242, 175, 41, 28);

        Dayin.setBackground(new java.awt.Color(255, 0, 255));
        Dayin.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Dayin.setForeground(new java.awt.Color(255, 255, 255));
        Dayin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Dayin.setToolTipText("");
        Dayin.setAlignmentX(0.0F);
        Dayin.setAutoscrolls(true);
        Dayin.setBorder(new javax.swing.border.MatteBorder(null));
        Dayin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(Dayin);
        Dayin.setBounds(293, 172, 59, 34);

        Month.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Month.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Month.setText("Month:");
        getContentPane().add(Month);
        Month.setBounds(356, 175, 58, 28);

        Monthin.setBackground(new java.awt.Color(0, 0, 255));
        Monthin.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Monthin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Monthin.setAlignmentX(0.0F);
        getContentPane().add(Monthin);
        Monthin.setBounds(418, 172, 122, 34);

        Year.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Year.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Year.setText("Year:");
        getContentPane().add(Year);
        Year.setBounds(544, 175, 43, 28);

        Yearin.setBackground(new java.awt.Color(0, 255, 0));
        Yearin.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Yearin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        Yearin.setAlignmentX(0.0F);
        getContentPane().add(Yearin);
        Yearin.setBounds(591, 172, 79, 34);

        Done.setBackground(new java.awt.Color(255, 255, 0));
        Done.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Done.setText("Done");
        Done.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Done.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Done.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });
        getContentPane().add(Done);
        Done.setBounds(670, 273, 75, 37);

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(763, 273, 63, 37);

        Output.setBackground(new java.awt.Color(0, 51, 153));
        Output.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        Output.setForeground(new java.awt.Color(102, 79, 253));
        Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Output);
        Output.setBounds(10, 217, 833, 55);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\ICS3UO\\3-balloons.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        String name, month;
        String day, year;
        name=namein.getText();
        day=(String) Dayin.getSelectedItem();
        month=(String) Monthin.getSelectedItem();
        year=(String) Yearin.getSelectedItem();
        Output.setText(name+"'s birthday is on "+day+" "+month+", "+year);
        
    }//GEN-LAST:event_DoneActionPerformed

    private void nameinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Birthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Birthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Birthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Birthday.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Birthday().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Day;
    private javax.swing.JComboBox<String> Dayin;
    private javax.swing.JButton Done;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Happy;
    private javax.swing.JLabel Month;
    private javax.swing.JComboBox<String> Monthin;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Output;
    private javax.swing.JLabel Year;
    private javax.swing.JComboBox<String> Yearin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namein;
    // End of variables declaration//GEN-END:variables
}
