/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package first.gui;

/**
 *
 * @author 843947
 */
public class Huricane extends javax.swing.JFrame {

    /**
     * Creates new form Huricane
     */
    public Huricane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        Hurricane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        hrhr = new javax.swing.JLabel();
        cat = new javax.swing.JLabel();
        catin = new javax.swing.JComboBox();
        valueout = new javax.swing.JLabel();
        valuein = new javax.swing.JTextField();
        disp = new javax.swing.JLabel();
        mess = new javax.swing.JLabel();
        DONE = new javax.swing.JButton();
        SELECT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));

        Hurricane.setMaximumSize(new java.awt.Dimension(1000, 1000));
        Hurricane.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\ICS3UO\\hurricane-hi.png")); // NOI18N
        jLabel2.setText("jLabel2");

        hrhr.setBackground(new java.awt.Color(51, 51, 255));
        hrhr.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        hrhr.setForeground(new java.awt.Color(255, 0, 51));
        hrhr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hrhr.setText("HURRICANE!!! HURRICANE!!!");

        cat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cat.setText("Category OR Speed:");

        catin.setBackground(new java.awt.Color(0, 255, 0));
        catin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catin.setMaximumRowCount(4);
        catin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Speed", "Category" }));

        valueout.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        valueout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        valuein.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valuein.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valuein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueinActionPerformed(evt);
            }
        });

        disp.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        disp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        mess.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        mess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        DONE.setBackground(new java.awt.Color(255, 0, 0));
        DONE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DONE.setText("DONE");
        DONE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DONEActionPerformed(evt);
            }
        });

        SELECT.setBackground(new java.awt.Color(102, 255, 255));
        SELECT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SELECT.setText("SELECT");
        SELECT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SELECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECTActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Kph");

        javax.swing.GroupLayout HurricaneLayout = new javax.swing.GroupLayout(Hurricane);
        Hurricane.setLayout(HurricaneLayout);
        HurricaneLayout.setHorizontalGroup(
            HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(hrhr, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(catin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(SELECT))
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(valueout, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(DONE, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(disp, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(valuein, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(cat))
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HurricaneLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        HurricaneLayout.setVerticalGroup(
            HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HurricaneLayout.createSequentialGroup()
                .addGroup(HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HurricaneLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(hrhr, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HurricaneLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(catin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SELECT))
                        .addGap(23, 23, 23)
                        .addGroup(HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DONE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HurricaneLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(valuein, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HurricaneLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(HurricaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HurricaneLayout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 23, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hurricane, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Hurricane, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueinActionPerformed

    private void SELECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECTActionPerformed
      String type;
      
      type=(String) catin.getSelectedItem();
       
      if("Speed".equals(type))
      {
          valueout.setText("Enter the speed of wind:");
      }
      else{
          valueout.setText("Enter the category of wind:") ;
     }
    }//GEN-LAST:event_SELECTActionPerformed

    private void DONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DONEActionPerformed
        float a;
        float b;
        String type;
      type=(String) catin.getSelectedItem();
        if("Speed".equals(type))
      {  
          valueout.setText("Enter the speed of wind:");
         a=Float.parseFloat(valuein.getText());
         if(a<=118)
         {
             disp.setText("This is not a hurricane!!!");
         }
        else if(a>=119&&a<=153)
         {
            disp.setText("This HURRICANE IS LEVEL 1.");
            mess.setText("You can go out of the house.");
         }
        else if(a>=154&&a<=177)
         {
            disp.setText("This HURRICANE IS LEVEL 2.");
             mess.setText("Close your doors and windows.");
         }
       else if(a>=178&&a<=209)
         {
            disp.setText("This HURRICANE IS LEVEL 3.");
             mess.setText("Watch Deadpool in your house.");
         }
       else if(a>=210&&a<=231)
         {
            disp.setText("This HURRICANE IS LEVEL 4.");
             mess.setText("Go to sleep.");
         }
       else{
           disp.setText("This HURRICANE IS LEVEL 5.");
            mess.setText("You are dead.");
       }
      }
        else if("Category".equals(type)){
       
            valueout.setText("Enter the category of wind:");
            b= Float.parseFloat(valuein.getText());
            if(b==1)
            {
               disp.setText("The speed range of hurricane is 119-153Km/hr.");
                mess.setText("You can go out of the house.");
            }
            else if(b==2)
            {
               disp.setText("The speed range of hurricane is 154-177Km/hr."); 
                mess.setText("Close your doors and windows.");
            }
            else if(b==3)
            {
               disp.setText("The speed range of hurricane is 178-209Km/hr."); 
                mess.setText("Watch Deadpool in your house.");
            }
           else if(b==4)
            {
               disp.setText("The speed range of hurricane is 210-231Km/hr.");
                mess.setText("Go to sleep.");
            }
           else if(b==5)
            {
               disp.setText("The speed range of hurricane is more than 232Km/hr."); 
            mess.setText("You are dead.");
            }
            else{
                disp.setText("Select the category betweeen 1-5.");
                 mess.setText("Pagla gaye ho kya! Budbak!");
                          }
        }
    }//GEN-LAST:event_DONEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Huricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Huricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Huricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Huricane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Huricane().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DONE;
    private javax.swing.JPanel Hurricane;
    private javax.swing.JButton SELECT;
    private javax.swing.JLabel cat;
    private javax.swing.JComboBox catin;
    private javax.swing.JLabel disp;
    private javax.swing.JLabel hrhr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel mess;
    private javax.swing.JTextField valuein;
    private javax.swing.JLabel valueout;
    // End of variables declaration//GEN-END:variables
}
