/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package first.gui;

/**
 *
 * @author 843947
 */
public class Pizza_price extends javax.swing.JFrame {

    /**
     * Creates new form Pizza_price
     */
    public Pizza_price() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        head = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        sizee = new javax.swing.JComboBox<String>();
        no = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        answer = new javax.swing.JLabel();
        value = new javax.swing.JLabel();
        noin = new javax.swing.JTextField();
        diamin = new javax.swing.JTextField();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        head.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        head.setForeground(new java.awt.Color(255, 255, 0));
        head.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        head.setText("Pizza Price Calcuator");
        getContentPane().add(head);
        head.setBounds(10, 10, 687, 62);

        size.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        size.setText("Size of your Pizza:");
        getContentPane().add(size);
        size.setBounds(10, 90, 88, 23);

        dia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dia.setText("Select a diameter:");
        getContentPane().add(dia);
        dia.setBounds(10, 130, 87, 23);

        sizee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sizee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large", "Extra Large" }));
        sizee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeeActionPerformed(evt);
            }
        });
        getContentPane().add(sizee);
        sizee.setBounds(120, 90, 81, 20);

        no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        no.setText("No. of Pizzas:");
        getContentPane().add(no);
        no.setBounds(10, 170, 88, 26);

        calculate.setBackground(new java.awt.Color(0, 0, 153));
        calculate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        calculate.setForeground(new java.awt.Color(0, 204, 51));
        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate);
        calculate.setBounds(290, 90, 227, 104);

        answer.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(answer);
        answer.setBounds(10, 237, 450, 154);

        value.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        value.setText("inches");
        getContentPane().add(value);
        value.setBounds(150, 130, 30, 14);

        noin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(noin);
        noin.setBounds(110, 170, 81, 20);

        diamin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(diamin);
        diamin.setBounds(110, 130, 37, 20);

        pic.setIcon(new javax.swing.ImageIcon("E:\\ICS3UO\\pizza3.png")); // NOI18N
        pic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(pic);
        pic.setBounds(-40, -50, 760, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        float price, SIZE, piz, num;
        SIZE=Float.parseFloat(diamin.getText());
        num=Float.parseFloat(noin.getText());
        piz=(float) ((SIZE*0.5)+2);
        price=piz*num;
        answer.setText("The total cost of your pizzas is $"+price);
          
    }//GEN-LAST:event_calculateActionPerformed

    private void sizeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza_price.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Pizza_price().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel answer;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel dia;
    private javax.swing.JTextField diamin;
    private javax.swing.JLabel head;
    private javax.swing.JLabel no;
    private javax.swing.JTextField noin;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel size;
    private javax.swing.JComboBox<String> sizee;
    private javax.swing.JLabel value;
    // End of variables declaration//GEN-END:variables
}
