/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.first.game;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author Karmit
 */
public class plSelector extends javax.swing.JFrame {

    /**
     * Creates new form plSelector
     */
    Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();
    int w = (int) ss.getWidth();
    int h = (int) ss.getHeight();
    int nw = w / 2, nh = h / 2;
    startForm sf = new startForm();
    
    public plSelector() {
        initComponents();

        screenSet();
        labelSet();
        keySet();
    }

    public void screenSet() {
        this.setSize(w / 2, h / 2);
        this.setLocation(w / 2 - w / 4, h / 2 - h / 4);
        this.setOpacity((float) 0.5);

        bkPanel.setLocation(this.getX(), this.getY());
        bkPanel.setSize(w / 2, h / 2);

        System.out.println("This Frame Size: " + this.getWidth() + this.getHeight());
        System.out.println("Back Panel Size: " + bkPanel.getWidth() + bkPanel.getHeight());
    }

    public void labelSet() {

        int lw = (nw / 4);
        int lh = (nh / 2);

        mode1.setSize(lw, lh);
        mode2.setSize(lw, lh);
        mode3.setSize(lw, lh);

        mode1.setLocation(lw / 4, this.getY() - lh / 2);
        mode2.setLocation(lw / 2 + lw, this.getY() - lh / 2);
        mode3.setLocation(lw * 3 / 4 + 2 * lw, this.getY() - lh / 2);

        mode1.setText("1");
        mode2.setText("2");
        mode3.setText("3");
    }

    public void keySet() {
        this.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                if (ke.getKeyCode() == KeyEvent.VK_LEFT) {
                    closeall();
                }
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    public void closeall()
    {
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkPanel = new javax.swing.JPanel();
        mode1 = new javax.swing.JLabel();
        mode2 = new javax.swing.JLabel();
        mode3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        bkPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.red, java.awt.Color.gray));
        bkPanel.setLayout(null);

        mode1.setBackground(new java.awt.Color(255, 255, 51));
        mode1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        mode1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mode1.setText("jLabel1");
        mode1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mode1MouseClicked(evt);
            }
        });
        bkPanel.add(mode1);
        mode1.setBounds(210, 80, 121, 46);

        mode2.setBackground(new java.awt.Color(0, 255, 0));
        mode2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        mode2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mode2.setText("jLabel1");
        mode2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mode2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mode2MouseClicked(evt);
            }
        });
        bkPanel.add(mode2);
        mode2.setBounds(370, 90, 121, 46);

        mode3.setBackground(new java.awt.Color(255, 0, 0));
        mode3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        mode3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mode3.setText("jLabel1");
        mode3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mode3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mode3MouseClicked(evt);
            }
        });
        bkPanel.add(mode3);
        mode3.setBounds(70, 90, 121, 46);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mode1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mode1MouseClicked
        new classicScreen().setVisible(true);
        sf.dispose();
        closeall();
    }//GEN-LAST:event_mode1MouseClicked

    private void mode2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mode2MouseClicked
        //new duelScreen().setVisible(true);
        closeall();
    }//GEN-LAST:event_mode2MouseClicked

    private void mode3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mode3MouseClicked
        // creativeScreen().setVisible(true);
        closeall();
    }//GEN-LAST:event_mode3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bkPanel;
    private javax.swing.JLabel mode1;
    private javax.swing.JLabel mode2;
    private javax.swing.JLabel mode3;
    // End of variables declaration//GEN-END:variables

}
