/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import javax.swing.ImageIcon;

/**
 *
 * @author karmi
 */
public class plsel extends javax.swing.JFrame
  {

    /**
     * Creates new form plsel
     */
    public plsel()
      {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setUndecorated(true);
        initComponents();
      }

    public String name1,name2;
    public ImageIcon x = new ImageIcon("src/tictactoe/Xss.png");
    public ImageIcon o = new ImageIcon("src/tictactoe/Os.png");
    public ImageIcon ic = new ImageIcon();
    public int count=0,order=2;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p1name = new javax.swing.JTextField();
        p2name = new javax.swing.JTextField();
        i1 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        swap = new javax.swing.JButton();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 595, 67));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Player 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 154, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Player 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 336, -1, -1));

        p1name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p1name.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                p1nameFocusLost(evt);
            }
        });
        p1name.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                p1nameActionPerformed(evt);
            }
        });
        getContentPane().add(p1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 151, 249, -1));

        p2name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        p2name.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                p2nameFocusLost(evt);
            }
        });
        getContentPane().add(p2name, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 333, 249, -1));

        i1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Os.png"))); // NOI18N
        getContentPane().add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 132, -1, -1));

        i2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/Xss.png"))); // NOI18N
        getContentPane().add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 313, -1, -1));

        swap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/ud.png"))); // NOI18N
        swap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                swapActionPerformed(evt);
            }
        });
        getContentPane().add(swap, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 227, 80, 80));

        next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 467, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1nameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_p1nameActionPerformed
    {//GEN-HEADEREND:event_p1nameActionPerformed
        
      name1=p1name.getText();
    }//GEN-LAST:event_p1nameActionPerformed

    private void p1nameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_p1nameFocusLost
    {//GEN-HEADEREND:event_p1nameFocusLost
         name1=p1name.getText();
    }//GEN-LAST:event_p1nameFocusLost

    private void p2nameFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_p2nameFocusLost
    {//GEN-HEADEREND:event_p2nameFocusLost
         name2=p2name.getText();
    }//GEN-LAST:event_p2nameFocusLost

    private void swapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_swapActionPerformed
    {//GEN-HEADEREND:event_swapActionPerformed
        count++;
        if(count%2==1)
          {
            i1.setIcon(x);
            i2.setIcon(o);
            order=1;
          }
        else if (count%2==0)
          {
            i2.setIcon(x);
            i1.setIcon(o);
            order=2;
          }
    }//GEN-LAST:event_swapActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backActionPerformed
    {//GEN-HEADEREND:event_backActionPerformed
        count=0;
        this.setVisible(false);
        new mainscreen().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nextActionPerformed
    {//GEN-HEADEREND:event_nextActionPerformed
      this.setVisible(false);  
      new pvp(name1,name2,order).setVisible(true);
      
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
      {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(plsel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(plsel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(plsel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(plsel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
          {
            public void run()
              {
                new mainscreen().setVisible(true);
              }
          });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton next;
    private javax.swing.JTextField p1name;
    private javax.swing.JTextField p2name;
    private javax.swing.JButton swap;
    // End of variables declaration//GEN-END:variables
  }
