/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author karmi
 */
public class pvp extends javax.swing.JFrame
  {

    /**
     * Creates new form pvp
     */
    public ImageIcon jbut = new ImageIcon("src/tictactoe/cardbackprs.jpg");
    public ImageIcon pic1 = new ImageIcon("src/tictactoe/X.png");
    public ImageIcon pic2 = new ImageIcon("src/tictactoe/O.png");
    public ImageIcon ic = new ImageIcon();
    public int[] place = new int[100];
    public int count = 0, p1w = 0, p2w = 0, orders;
    public Boolean winner = false;
    public String names1, names2;
    plsel l = new plsel();

    public pvp(String an1,String an2,int orders)
      {
        this.setUndecorated(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        this.names1=an1;
        this.names2=an2;
        this.orders = l.order;
        if (orders == 2)
          {
            pic1 = new ImageIcon("src/tictactoe/O.png");
            pic2 = new ImageIcon("src/tictactoe/X.png");
          }
        else if(orders==1)
          {
            pic1 = new ImageIcon("src/tictactoe/X.png");
            pic2 = new ImageIcon("src/tictactoe/O.png");
          }
        if (an1 == null)
          {
            this.names1 = "Player 1";
          }
        if (an2 == null)
          {
            this.names2 = "Player 2";
          }
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        replay = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        onewins = new javax.swing.JLabel();
        twowins = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b1ActionPerformed(evt);
            }
        });

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b2ActionPerformed(evt);
            }
        });

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b3ActionPerformed(evt);
            }
        });

        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b4ActionPerformed(evt);
            }
        });

        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b5ActionPerformed(evt);
            }
        });

        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b6ActionPerformed(evt);
            }
        });

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b7ActionPerformed(evt);
            }
        });

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b8ActionPerformed(evt);
            }
        });

        b9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/cardbackprs.jpg"))); // NOI18N
        b9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                b9ActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitActionPerformed(evt);
            }
        });

        replay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        replay.setText("Replay");
        replay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                replayActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        onewins.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        twowins.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exit)
                                    .addComponent(replay)
                                    .addComponent(jButton2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(onewins, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twowins, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exit)
                        .addGap(20, 20, 20)
                        .addComponent(replay)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onewins, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twowins, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b1ActionPerformed
    {//GEN-HEADEREND:event_b1ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(1);
        check();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b2ActionPerformed
    {//GEN-HEADEREND:event_b2ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(2);
        check();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b3ActionPerformed
    {//GEN-HEADEREND:event_b3ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(3);
        check();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b4ActionPerformed
    {//GEN-HEADEREND:event_b4ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(4);
        check();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b5ActionPerformed
    {//GEN-HEADEREND:event_b5ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(5);
        check();
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b6ActionPerformed
    {//GEN-HEADEREND:event_b6ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(6);
        check();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b7ActionPerformed
    {//GEN-HEADEREND:event_b7ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(7);
        check();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b8ActionPerformed
    {//GEN-HEADEREND:event_b8ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(8);
        check();
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_b9ActionPerformed
    {//GEN-HEADEREND:event_b9ActionPerformed
        count++;
        System.out.println("" + count);
        seticon(9);
        check();
    }//GEN-LAST:event_b9ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitActionPerformed
    {//GEN-HEADEREND:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void replayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_replayActionPerformed
    {//GEN-HEADEREND:event_replayActionPerformed
        reset();
    }//GEN-LAST:event_replayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        reset();
        p1w = 0;
        p2w = 0;
        onewins.setText(null);
        twowins.setText(null);
        this.setVisible(false);
        new mainscreen().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void seticon(int n)
      {
        if (count % 2 == 1)
          {
            ic = pic1;
            switch (n)
              {
                case 1:
                    b1.setEnabled(false);
                    b1.setDisabledIcon(ic);
                    place[1] = 1;
                    break;
                case 2:
                    b2.setEnabled(false);
                    b2.setDisabledIcon(ic);
                    place[2] = 1;
                    break;
                case 3:
                    b3.setEnabled(false);
                    b3.setDisabledIcon(ic);
                    place[3] = 1;
                    break;
                case 4:
                    b4.setEnabled(false);
                    b4.setDisabledIcon(ic);
                    place[4] = 1;
                    break;
                case 5:
                    b5.setEnabled(false);
                    b5.setDisabledIcon(ic);
                    place[5] = 1;
                    break;
                case 6:
                    b6.setEnabled(false);
                    b6.setDisabledIcon(ic);
                    place[6] = 1;
                    break;
                case 7:
                    b7.setEnabled(false);
                    b7.setDisabledIcon(ic);
                    place[7] = 1;
                    break;
                case 8:
                    b8.setEnabled(false);
                    b8.setDisabledIcon(ic);
                    place[8] = 1;
                    break;
                case 9:
                    b9.setEnabled(false);
                    b9.setDisabledIcon(ic);
                    place[9] = 1;
                    break;
              }
          }
        if (count % 2 == 0)
          {
            ic = pic2;
            switch (n)
              {
                case 1:
                    b1.setEnabled(false);
                    b1.setDisabledIcon(ic);
                    place[1] = 2;
                    break;
                case 2:
                    b2.setEnabled(false);
                    b2.setDisabledIcon(ic);
                    place[2] = 2;
                    break;
                case 3:
                    b3.setEnabled(false);
                    b3.setDisabledIcon(ic);
                    place[3] = 2;
                    break;
                case 4:
                    b4.setEnabled(false);
                    b4.setDisabledIcon(ic);
                    place[4] = 2;
                    break;
                case 5:
                    b5.setEnabled(false);
                    b5.setDisabledIcon(ic);
                    place[5] = 2;
                    break;
                case 6:
                    b6.setEnabled(false);
                    b6.setDisabledIcon(ic);
                    place[6] = 2;
                    break;
                case 7:
                    b7.setEnabled(false);
                    b7.setDisabledIcon(ic);
                    place[7] = 2;
                    break;
                case 8:
                    b8.setEnabled(false);
                    b8.setDisabledIcon(ic);
                    place[8] = 2;
                    break;
                case 9:
                    b9.setEnabled(false);
                    b9.setDisabledIcon(ic);
                    place[9] = 2;
                    break;
              }
          }
      }

    public void check()
      {
        if (place[1] == 1 && place[4] == 1 && place[7] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[2] == 1 && place[5] == 1 && place[8] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[3] == 1 && place[6] == 1 && place[9] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[1] == 1 && place[2] == 1 && place[3] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[4] == 1 && place[5] == 1 && place[6] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[7] == 1 && place[8] == 1 && place[9] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[1] == 1 && place[5] == 1 && place[9] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[3] == 1 && place[5] == 1 && place[7] == 1)
          {
            JOptionPane.showMessageDialog(null, names1 + " won!!!");
            winner = true;
            p1w++;
            onewins.setText(names1 + " Wins:" + p1w);
            reset();
          }
        if (place[1] == 2 && place[4] == 2 && place[7] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[2] == 2 && place[5] == 2 && place[8] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[3] == 2 && place[6] == 2 && place[9] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[1] == 2 && place[2] == 2 && place[3] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[4] == 2 && place[5] == 2 && place[6] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[7] == 2 && place[8] == 2 && place[9] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[1] == 2 && place[5] == 2 && place[9] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (place[3] == 2 && place[5] == 2 && place[7] == 2)
          {
            JOptionPane.showMessageDialog(null, names2 + " won!!!");
            winner = true;
            p2w++;
            twowins.setText(names2 + " Wins:" + p2w);
            reset();
          }
        if (count == 9)
          {
            if (winner == false)
              {
                JOptionPane.showMessageDialog(null, "It's a draw! Play Again!");
                reset();
              }
          }

      }

    public void reset()
      {
        b1.setEnabled(true);
        b2.setEnabled(true);
        b3.setEnabled(true);
        b4.setEnabled(true);
        b5.setEnabled(true);
        b6.setEnabled(true);
        b7.setEnabled(true);
        b8.setEnabled(true);
        b9.setEnabled(true);
        b1.setIcon(jbut);
        b2.setIcon(jbut);
        b3.setIcon(jbut);
        b4.setIcon(jbut);
        b5.setIcon(jbut);
        b6.setIcon(jbut);
        b7.setIcon(jbut);
        b8.setIcon(jbut);
        b9.setIcon(jbut);
        for (int i = 1; i <= 10; i++)
          {
            place[i] = 0;
          }
        count = 0;
      }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
      {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(pvp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
          {
            public void run()
              {
                new mainscreen().setVisible(true);
              }
          });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel onewins;
    private javax.swing.JButton replay;
    private javax.swing.JLabel twowins;
    // End of variables declaration//GEN-END:variables
  }
