/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package timer;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author 843947
 */
public class btn extends javax.swing.JFrame
  {

    Timer t, ti;
    int i, x, y, time = 500;
    JLabel[] j = new JLabel[100];

    /**
     * Creates new form BTW
     */
    public btn()
      {
        initComponents();

        j[0] = jLabel1;
        j[1] = jLabel2;
        j[2] = jLabel3;
        j[3] = jLabel4;
        j[4] = jLabel5;
        j[5] = jLabel6;
        j[6] = jLabel7;
        j[7] = jLabel8;

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jLabel1.setText("Number 1");
        getContentPane().add(jLabel1);

        jLabel2.setText("Number 2");
        getContentPane().add(jLabel2);

        jLabel3.setText("Number 3");
        getContentPane().add(jLabel3);

        jLabel4.setText("Number 4");
        getContentPane().add(jLabel4);

        jLabel5.setText("Number 5");
        getContentPane().add(jLabel5);

        jLabel6.setText("Number 6");
        getContentPane().add(jLabel6);

        jLabel7.setText("Number 7");
        getContentPane().add(jLabel7);

        jLabel8.setText("Number 8");
        getContentPane().add(jLabel8);

        start.setText("Press Me");
        start.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        for (i = 0; i <= 7; i++)
          {
            j[i].setVisible(false);
          }
        j[0].setVisible(true);
        x = 0;
        y = 0;
        t = new Timer(time, new ActionListener()
          {
            @Override
            public void actionPerformed(ActionEvent e)
              {
                x++;
                if (x >= 14)
                  {
                    j[y].setVisible(false);
//                        x=0;
                    t.stop();
                  }

                if (x > 0)
                  {
                    if (x % 2 == 1)
                      {
                        y = (x + 1) / 2;
                        System.out.println("" + x + y);
                        j[y].setVisible(false);
                        j[y - 1].setVisible(false);
                      } else
                      {
                        y = x / 2;
                        System.out.println("" + x + y);
                        j[y - 1].setVisible(false);
                        j[y].setVisible(true);
                      }

                  }
              }
          }
        );
        t.start();
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
      {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Nimbus".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                  }
              }
          } catch (ClassNotFoundException ex)
          {
            java.util.logging.Logger.getLogger(btn.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

          } catch (InstantiationException ex)
          {
            java.util.logging.Logger.getLogger(btn.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

          } catch (IllegalAccessException ex)
          {
            java.util.logging.Logger.getLogger(btn.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

          } catch (javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(btn.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
          {
            public void run()
              {
                new btn().setVisible(true);
              }
          });
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
